name: Build and push Docker image to docker hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: ${{ github.workspace }}/target/*.jar
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create target dir
        run: mkdir -p target
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v1
        with:
            name: jar-artifact
            path: target/
      - name: Check that artifact exists
        run: pwd && ls -lart target/
      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_TOKEN
      - name: Create SHORT_SHA env var
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build the Docker image
        run: docker build -t korteke/text4shell:${SHORT_SHA} .

      - name: Push Docker image to registry
        run: docker push korteke/text4shell:${SHORT_SHA}